KovDimaY/React-Highcharts

src/components/charts/pie.js
src/constants/pie/data-helpers-pie.js
styles/charts/pie.scss

This is a PR to test how it works on GitHub

Dev 1 - Test PR

---

src/components/charts/pie.js
src/constants/pie/data-helpers-pie.js
src/constants/pie/default-options-pie.js
src/constants/pie/modes-options-pie.js
styles/charts/bar.scss
styles/charts/pie.scss

You can see details in the issue description: [Issue #6](https://github.com/KovDimaY/React-Highcharts/issues/6)

Dev 4 - Finished Pie chart page

---

README.md
src/components/charts/bar.js
src/components/charts/pie.js
src/components/home.js
src/constants/bar/default-options-bar.js
src/constants/pie/default-options-pie.js
styles/charts/bar.scss
styles/charts/line.scss
styles/charts/pie.scss

You can see descriptions in [Issue DEV-6 #10 ](https://github.com/KovDimaY/React-Highcharts/issues/10)

Dev 6 - Deployment to production

---

README.md
package.json

Dev 14 - updated README.md

---

src/components/charts/line.js
src/constants/line/data-helpers-line.js
src/constants/line/default-options-line.js
src/constants/line/modes-options-line.js

Dev-12: LineChart added area to PureRandom mode

---

src/components/charts/bar.js
src/constants/bar/default-options-bar.js
src/constants/bar/modes-options-bar.js

DEV-13 stacked more added to PR of bar chart

---

.gitignore
index.html
src/components/charts/bar.js
src/components/charts/line.js
src/components/charts/pie.js
src/components/tooltip.js
src/constants/bar/modes-options-bar.js
src/constants/line/modes-options-line.js
src/constants/pie/default-options-pie.js
src/constants/pie/modes-options-pie.js
styles/charts/bar.scss
styles/charts/line.scss
styles/charts/pie.scss
styles/index.scss
styles/tooltip.scss

Dev 10 - Added a tooltip with info about modes

---

src/components/charts/line.js
src/constants/line/data-helpers-line.js
src/constants/line/modes-options-line.js

Dev 16 - Correct tooltips (Line Chart)

---

src/constants/bar/modes-options-bar.js

Dev 17 - Correct tooltips (Bar Chart)

---

src/components/charts/scatter.js
src/constants/scatter/data-helpers-scatter.js
src/constants/scatter/default-options-scatter.js
src/constants/scatter/modes-options-scatter.js
styles/charts/scatter.scss

Dev 7 - Implemented Configurable Random section for Scattering

---

package.json
src/components/charts/other.js
src/components/color-picker.jsx
src/constants/line/default-options-line.js
src/constants/other/data-helpers-other.js
src/constants/other/default-options-other.js
src/constants/other/modes-options-other.js
styles/charts/other.scss

Dev 21 - Heatmap functionality

---

src/components/charts/other.js
src/constants/other/data-helpers-other.js
src/constants/other/default-options-other.js
src/constants/other/modes-options-other.js
styles/charts/other.scss

Dev 23 - Polar functionality

---

src/constants/other/default-options-other.js

Some small configuration was missed.

Dev 25 - fixed a small visual issue with the tooltip

---

src/components/footer.js
styles/footer.scss

Dev 19 -  Temporary solution, implemented a simple link

---

src/components/charts/other.js
src/constants/other/data-helpers-other.js
src/constants/other/default-options-other.js
src/constants/other/modes-options-other.js
styles/charts/other.scss

Dev 28 - Pyramid functionality

---

src/components/charts/other.js
src/constants/other/data-helpers-other.js
src/constants/other/default-options-other.js
src/constants/other/modes-options-other.js
src/constants/shared/helpers.js
styles/charts/other.scss

Dev 26 - Activity Gauge functionality

---

src/components/header.js

DEV-30 Replace links to react-router links #58

---

index.html
src/routes.js

There was a simple problem with path for static files. You should use an absolute path for it.
https://github.com/ReactTraining/react-router/blob/master/FAQ.md#why-doesnt-my-application-work-when-loading-nested-routes
At first, I thought that problem connected with react-router, but I was wrong.
Also I've changed **routes.js**, because, as I know, the app should has one **Router** and different **Route** to render UI.

DEV-34 replace relative path for static files on absolute; changes routes

---

src/components/charts/other.js
src/constants/other/data-helpers-other.js
src/constants/other/default-options-other.js
src/constants/other/modes-options-other.js
src/constants/shared/helpers.js
styles/charts/other.scss

Dev 24 - Boxplot functionality

---

src/components/charts/bar.js

DEV-35 fixed problem of the broken mode in Bar Charts

---

package-lock.json
package.json

Closes https://github.com/KovDimaY/React-Highcharts/issues/73
What I did:
- **Install prettier**.
- **Install husky**.
- **Write a husky hook to execute prettier on commit**.
- **Update Node from 8 to 10.13.0**. Husky requires Node 10. And prettier 10.13.0
Example of commit I did in my forked repo:
Happy hacktoberfest @KovDimaY

Add prettier and husky to execute prettier on commit
